@startuml

title "Manage Message Shop(GET)"

participant Client
participant Server
participant MessageShopRouter as "MessageShopRouter"
participant Middleware
participant MessageShopController as "MessageShopController"
participant MessageShopModel as "MessageShopModel"
database "<<MongoDB>>\n:message_shops" as MessageShopDatabase

Client -> Server: req.post('/api/v1/massage-shops')
activate Server
Server -> MessageShopRouter: app.use("/api/v1", verifyToken, getAllMassageShops)
activate MessageShopRouter

MessageShopRouter -> Middleware: verifyToken()
activate Middleware
Middleware -> Middleware: Extract token from headers
activate Middleware
deactivate Middleware


alt Token is missing
    Middleware --> Client: 401 Unauthorized (TKN_6001)
else Token is blacklisted
    Middleware --> Client: 401 Unauthorized (TKN_6002)
else Token is valid
    Middleware --> MessageShopRouter: next()
deactivate Middleware
end

MessageShopRouter -> MessageShopController: getAllMassageShops(req, res)
deactivate MessageShopRouter
activate MessageShopController

MessageShopController -> MessageShopModel: find()
activate MessageShopModel
MessageShopModel -> MessageShopDatabase: MessageShopSchema
activate MessageShopDatabase
MessageShopDatabase --> MessageShopModel: message shops
deactivate MessageShopDatabase
deactivate MessageShopModel
alt not found message shops
    MessageShopController -> Client: 404 NOT_FOUND
else found message shops
    MessageShopController -> MessageShopModel: countDocuments()
    activate MessageShopModel
    MessageShopModel -> MessageShopDatabase: MessageShopSchema
    activate MessageShopDatabase
    MessageShopDatabase --> MessageShopModel: counts
    deactivate MessageShopDatabase
    deactivate MessageShopModel
    MessageShopController --> Server: Response Data
        deactivate MessageShopController
alt Get reservation successfully
    Server --> Client: 200 OK (RSV_3005)
else Internal Server Error   
    Server --> Client: 500 SERVER_ERROR (GNR_1001)
    deactivate Server
end
end

@enduml
