@startuml

title "Manage Message Rervation(GET)"

participant Client
participant Server
participant ReservationRouter as "ReservationRouter"
participant Middleware
participant ReservationController as "ReservationController"
participant ReservationModel as "ReservationModel"
database "<<MongoDB>>\n:reservations" as ReservationDatabase

Client -> Server: req.post('/api/v1/booking')
activate Server
Server -> ReservationRouter: app.use("/api/v1", verifyToken, getReservation)
activate ReservationRouter

ReservationRouter -> Middleware: verifyToken()
activate Middleware
Middleware -> Middleware: Extract token from headers
activate Middleware
deactivate Middleware


alt Token is missing
    Middleware --> Client: 401 Unauthorized (TKN_6001)
else Token is blacklisted
    Middleware --> Client: 401 Unauthorized (TKN_6002)
else Token is valid
    Middleware --> ReservationRouter: next()
deactivate Middleware
end

ReservationRouter -> ReservationController: getReservation(req, res)
deactivate ReservationRouter
activate ReservationController

alt Account is Admin and not request specific data
    ReservationController -> ReservationModel: runAggregation(isAdmin,req.query,userId,skip,limit)
    activate ReservationModel
    ReservationModel -> ReservationDatabase: ReservationSchema
    activate ReservationDatabase
    ReservationDatabase --> ReservationModel: resvations 
    deactivate ReservationDatabase
    deactivate ReservationModel
else  Account is Admin request specific data
    ReservationController -> ReservationModel: runAggregation(isAdmin)
    activate ReservationModel
    ReservationModel -> ReservationDatabase: ReservationSchema
    activate ReservationDatabase
    ReservationDatabase --> ReservationModel: resvations 
    deactivate ReservationDatabase
    deactivate ReservationModel
else Account is User and not request specific data
    ReservationController -> ReservationModel: runAggregation(isAdmin,req.query,userId,skip,limit)
    activate ReservationModel
    ReservationModel -> ReservationDatabase: ReservationSchema
    activate ReservationDatabase
    ReservationDatabase --> ReservationModel: resvations 
    deactivate ReservationDatabase
    deactivate ReservationModel
else  Account is User request specific data
    ReservationController -> ReservationModel: runAggregation(isAdmin,null,userId,skip,limit)
    activate ReservationModel
    ReservationModel -> ReservationDatabase: ReservationSchema
    activate ReservationDatabase
    ReservationDatabase --> ReservationModel: resvations 
    deactivate ReservationDatabase
    deactivate ReservationModel
end

    ' ReservationController --> Server: Response Data
    ' deactivate Server
alt Get reservation successfully
    ReservationController --> Client: 200 OK (RSV_3005)
else Internal Server Error   
    ReservationController --> Client: 500 SERVER_ERROR (GNR_1001)
    deactivate ReservationController
end

@enduml
