@startuml
left to right direction

actor Customer
actor Member
actor Admin
' database Account
' database Reservation
' database Point

rectangle "Massage Reservation" {
    usecase "Register" as Register
    usecase "Login" as Login
    
    usecase "Book massage reservation" as Book
    usecase "View massage reservation" as View
    usecase "Edit massage reservation" as Edit
    usecase "Delete massage reservation" as Delete

    usecase "View any massage reservation" as ViewAny
    usecase "Edit any massage reservation" as EditAny
    usecase "Delete any massage reservation" as DeleteAny
}

Customer -- Register
Member -- Login

Member -- Book
Member -- View
Member -- Edit
Member -- Delete


Admin -- ViewAny
Admin -- EditAny
Admin -- DeleteAny

' Register -- Account
' Login -- Account

' Book -- Reservation
' View -- Reservation
' Edit -- Reservation
' Delete -- Reservation

' Book -- Point

' ViewAny -- Reservation
' EditAny -- Reservation
' DeleteAny -- Reservation


@enduml
