@startuml
participant Client
participant Server
participant ReservationRouter as "ReservationRouter"
participant VerifyToken
participant ValidateParam
participant ValidateBody
participant ReservationController as "ReservationController"
participant ReservationModel as "ReservationModel"
participant SlackService

Client -> Server: req.put('/api/v1/booking/:id')
activate Server
Server -> ReservationRouter: app.use("/api/v1", verifyToken, validateParam, updateReservation)
activate ReservationRouter

ReservationRouter -> VerifyToken: verifyToken()
activate VerifyToken
VerifyToken -> VerifyToken: Extract token from headers
activate VerifyToken
deactivate VerifyToken

alt Token is missing
    VerifyToken --> Client: 401 Unauthorized (TKN_6001)
else Token is blacklisted
    VerifyToken --> Client: 401 Unauthorized (TKN_6002)
else Token is valid
    VerifyToken -> ReservationRouter: next()
    deactivate VerifyToken
end

ReservationRouter -> ValidateParam: validateParam(bookingRunningSchema)

activate ValidateParam
alt Invalid data format
    ValidateParam --> Client: 400 Invalid data format (VAL_4004)
else data format is valid    
    ValidateParam -> ReservationRouter:  next()
end
deactivate ValidateParam

ReservationRouter -> ValidateBody: validateBody(bodyPutSchema)
activate ValidateBody
alt Invalid data format
    ValidateBody --> Client: 400 Invalid data format (VAL_4004)
else data format is valid    
    ValidateBody -> ReservationRouter:  next()
end
deactivate ValidateBody

ReservationRouter -> ReservationController: updateReservation(req, res)
deactivate ReservationRouter

activate ReservationController

ReservationController -> ReservationModel: updateWithRole(isAdmin,userId,bookingId,req.body)
activate ReservationModel

alt role Admin
    ReservationModel -> ReservationModel: findOneAndUpdate(date, shopId, userId)
    activate ReservationModel
    deactivate ReservationModel
else role User
    ReservationModel -> ReservationModel: findOneAndUpdate(date, shopId)
    activate ReservationModel
    deactivate ReservationModel
end

ReservationModel --> ReservationController: Response with reservation data
deactivate ReservationModel

ReservationController -> SlackService: sendSlack()
activate SlackService
deactivate SlackService
ReservationController --> Server: Response data
deactivate ReservationController

alt Update reservation successfully
    Server --> Client: 200 OK (RSV_3010)
else Update reservation failed Reservation not found
    Server --> Client: 404 NOT FOUND (RSV_3004)
else Internal Server Error
    Server -> Client: 500 SERVER_ERROR (GNR_1001)
end
@enduml
